export default {
  owner_item_list: [
    // Relics
    'spharai',
    'mandau',
    'excalibur',
    'ragnarok',
    'guttler',
    'bravura',
    'apocalypse',
    'gugnir',
    'kikoku',
    'amanomurakumo',
    'mjollnir',
    'claustrum',
    'yoichinoyumi',
    'annihilator',
    'gjallarhorn',
    'aegis',
    // Mythics
    'conqueror',
    'glanzfaust',
    'yagrush',
    'laevateinn',
    'murgleis',
    'vajra',
    'burtgang',
    'liberator',
    'aymur',
    'carnwenhan',
    'gastraphetes',
    'kogarasumaru',
    'nagi',
    'ryunohige',
    'nirvana',
    'tizona',
    'death_penalty',
    'kenkonken',
    'terpischore',
    'tupsimati',
    // Misc
    'ebisu_fishing_rod',
    'defending_ring',
  ],
};
