module.exports = {
  features: {
    login: false,
    registration: false,
    changePassword: false,
    changeEmail: false,
  },
  posts: [
    {
      date: '2020-02-19T23:27:48.649Z',
      author: 'Godmode',
      title: 'Welcome back!',
      message:
        "The new website tools are now live. Please bear with us as some issues arise that were not found during testing. The website is not optimized for smaller views (i.e. mobile) but someone can submit a pull request for styling it. Constructive feedback, bug reports, and feature requests on all parts is appreciated and can be submited via an issue on this GitHub repo. Please find that I wrote the new website using a clean and minimalist design approach and it may take some time to learn to navigate it if you are used to the old website. Pages can be found in the menu by clicking the icon in the top left corner. If you're an artist and would like to contribute some designs to the website please create a ticket or PR with designs. I will not be actively contributing to this project other than reviewing pull requests.",
    },
  ],
  rules: {
    terms: [
      'You will be watched from time to time by the active/hidden GM team that patrols and responds to reports for cheating.',
      'Like most online games, Eden will collect and store data from you such as IP addresses, MAC addresses, and other unique device identifiers to help curb cheating.',
      'You will follow the server rules listed below. ALL rules may be met with punishment including up to a ban on all Eden content.',
      'You will not engage in any manner to profit from the work of SQUARE ENIX CO., LTD. or the Eden staff. This includes the selling of accounts, gil or items.',
      'These terms may change at any time. Each time you connect to Eden you are bound to the terms as they are posted here.',
      'You acknowledge that we are not affiliated in any way with SQUARE ENIX CO., LTD.',
      'You acknowledge that SQUARE ENIX CO., LTD. is the owner of all FINAL FANTASY® XI content and images with all rights reserved.',
      'You acknowledge that Eden has no ownership over or affiliation with any of the content, images, registered trademarks or any other rights reserved by SQUARE ENIX CO., LTD.',
    ],
    rules: [
      /*
                        'Using a non-Eden bootloader--including using a modified version of the Eden bootloader--is NOT allowed. The bootloader must be downloaded from the official site or #annoucements channel in our official Discord otherwise there are no guarantees it is official.',
                        'Until a technical solution is implemented, no more than 8 monsters may be intentionally gathered to kill at the same time.',
                        'If something feels like it is broken, either not like it was on era retail or a potential exploit or too overpowered. (read: if something seems like it was not intentional from the development team) report it. Knowingly taking advantage of these activities is NOT allowed.',
                        'Each player is only allowed to have 2 characters logged in and active, with an additional third character confined to a city and idle. This character may only be used to bazaar or mule items while your other characters are logged in. (This will not be locked down by IP, but it will be actively patrolled.) Tri-boxing 3 or more active characters is NOT allowed.',
                        'Claim bots, modifying dats to claim, any type of targeting using mob id (such as /target 12345678) or using any other third party tools such as Shorthand or its Windower equivalent to claim is NOT allowed.',
                        "Any scripts, bots, or addons that automate actions are NOT allowed. Macros using the /wait or <wait> feature within the game are OK. (Such as /lastsynth macros up to the game's maximum of 6 lines.)",
                        "Account sharing is strongly discouraged and may be disallowed in the future. If one or more of your accounts are linked to a player that is caught cheating by either logging into an offending player's account or by that player logging into one of your accounts you will share the same punishment as the cheater--which is 9 out of 10 times a permanent ban.",
                        'Not really a rule but be aware that players may be limited in the future to 3 characters. So create new ones at your own risk. It is undecided how additional characters would be handled if we imposed these limits.',
                        'Using known bugs (including terrain) or unpatched exploits to your advantage in a way that would not be possible in retail. For example: purposefully crawling on walls to avoid aggro using the current navmesh’s bugs is NOT allowed. (Note: this does not mean people are exploiting because they are standing on walls. It is a normal reaction to be on a wall. But climbing through tight spaces without oils and powders without aggro is obviously a bug and you will be banned for it.)',
                        'Testing known or possible exploits on the live server is not allowed unless permission is given from Godmode first. Like every other rule this includes GMs and developers too.',
                        "Holding a monster for the purpose of grieving other players or monopolizing the time it spawns is NOT allowed (note that since determining a player's intent is highly subjective to the GM addressing the ticket, if asked to begin damage by a GM you must start fighting the monster within a reasonable amount of time or you will forfeit the claim)",
                        "Reasonable is up to the GM team's discretion.",
                        '    ^Holding to recover from a wipe is allowed.',
                        "Darters in Dragon's Aery may be held alive 5 minutes from time of claim. Period. Please see #announcements or ask a GM for more information if you need it.",
                        "    ^Intention to kill with reinforcements on the way isn't holding.",
                        "Not so much a rule either but if you are aware of any non-era item/NM/recipe/et cetera please report it. And do expect the rewards obtained from it to be removed. I can't find every non-era thing at once but as I find them I will be removing them.",
                        'Creating characters for the purpose of market manipulation is NOT allowed.',
                        'Gardening is only allowed on up to 3 characters. (30 total plants.)',
                        'Hacking/exploiting/cheating of any kind including but not limited to buying items and selling back for more than you paid for is NOT allowed.',
                        'Spamming any public chat. (Linkshells and tells are the exception as they will only be subject to harassment reports.)',
                        'Harassment of any kind including offensive character or linkshell names is NOT allowed.',
                        'Character names that depict cheating, could be considered sexually explicit, or any names that could be disallowed on retail are NOT allowed.',
                        'Use of or advertisement of any cheat program/addon or a non-approved addon/program on Eden or its media. There will be an allowed list and a non-allowed list. Those not in the approved list are discouraged from use as you may be penalized for using them. Use at your own risk. Those that are similar to a forbidden program are most likely forbidden as well.',
                        'GM interaction is limited here but if a GM messages you in game and you are active, respond within a reasonable time. Ignoring a GM is likely to get you jailed as we will likely think you are afk botting.',
                   added directly to rules page for formatting
                   */
    ],

    allowedashita: [
      'Affinity',
      'Antiemote',
      'Ashitacast Not to be used for actions based on what a mob does etc)',
      'Aspect',
      'Autojoin',
      'Barfiller',
      'Battlemod',
      'Blumon',
      'Blusets',
      'Cfhblock',
      'Chamcham',
      'Changecall',
      'Chatmon',
      'Checker',
      'Clock',
      'Craftmon',
      'Dashcam',
      'Dats',
      'Debuff',
      'Deeps',
      'Drawdistance',
      'Dressme',
      'Duration',
      'Enternity',
      'ExpMon',
      'FFXIvision',
      'FFXIVbar',
      'Filterless',
      'Filters',
      'Findall',
      'Find',
      'Giltracker',
      'Gearlock',
      'Greed',
      'Hardwaremouse',
      'Ibar',
      'Ime',
      'Imguistyle',
      'Instantah',
      'Itemwatch',
      'Kparser',
      'Links',
      'Logs',
      'Macrofix',
      'Mountmuzzle',
      'PartyBuffs',
      'Pbar',
      'Petinfo',
      'Recast',
      'RollTracker',
      'Scoreboard',
      'Sexchange',
      'Shorthand(Never',
      'for',
      'claiming) ',
      'Singlerace',
      'Skillchain',
      'Status',
      'Statustimers',
      'Stfu',
      'Watchexp',
      'Xiview',
    ],
    disallowedashita: [
      'Ahgo',
      'Allmaps',
      'Bellhop',
      'Crafty',
      'Gateway',
      'Filterscan',
      'Ja0wait',
      'Lootwhore',
      'Lotomatic',
      'Mapdot',
      'Minimap',
      'Multisend',
      'No - ckback',
      'Nomad Onevent',
      'Paranormal',
      'Peekaboo',
      'Repeat',
      'Repeater',
      'Servo',
      'Skeletonkey',
      'Synplicity',
      'Watchdog',
      'Zoom',
      'Notes: Wireframe / Fillmode - Allowed unless you use it for pulling things through the floor or wall you couldnt normally target -- ESPECIALLY/MAINLY in a competitive environment (NM or otherwise)',
    ],
    allowedwindower: [
      'AutoInvite',
      'AutoJoin',
      'AzureSets',
      'Barfiller',
      'Battlemod',
      'Binder',
      'Blist',
      'BLUAlert',
      'BluGuide',
      'Cancel',
      'Chars',
      'Chatmon',
      'Clock',
      'Config',
      'ConsoleBG',
      'DelayMeNot',
      'Digger',
      'Distance',
      'DistancePlus',
      'DressUp',
      'EnemyBar',
      'Enternity',
      'FindAll',
      'FishingCrashFix',
      'GameTime',
      'Gearswap(Not to be used for actions based on what a mob does',
      'etc) Highlight',
      'IME',
      'InfoBar',
      'InfoReplacer',
      'InstaLS',
      'LatentChecker',
      'Linker',
      'Logger',
      'OhShi',
      'MacroChanger',
      'Nostrum',
      'PetTP',
      'Plugin',
      'Manager',
      'Pouches',
      'Respond',
      'Rhombus',
      'RollTracker',
      'Scoreboard',
      'SetBGM',
      'Shortcuts(Never for claiming)',
      'Skillchain',
      'SpeedChecker',
      'SpellCheck',
      'SSOrganiser',
      'Stopwatch',
      'Text',
      'Tickle',
      'Timers',
      'Timestamp',
      'TParty',
      'Translate',
      'TreasurePool',
      'Update',
      'Weathermon',
      'WinControl',
      'XIVBar',
      'ZoneTimer',
    ],
    disallowedwindower: [
      'AEcho',
      'AnnounceTarget',
      'AnsweringMachine',
      'AutoControl',
      'AutoExec',
      'AutoRA',
      'Cellhelp',
      'Chatporter',
      'Craft',
      'DynamisHelper',
      'Eval',
      'FastCS',
      'FFXIDB',
      'Itemizer',
      'Ja0wait',
      'JobChange',
      'MobCompass',
      'ObiAway',
      'Organizer',
      'Run',
      'Send',
      'STNA',
      'SubTarget',
      'Targetinfo',
      'Treasury',
      'Yush',
    ],
    yells: [
      'Do not yell profanity, hate messages or any harassing statements. This is a global chat. Violating this rule may result in a character ban as well.',
      'Do not banter back and forth between yourselves. This includes replying in yell to someone who has violated the rules.',
      'Asking a legitimate FFXI question in yell is fine. Replies to questions should be sent in /tells, not in /yell.',
      "Yell rules may change from time to time. If this happens we will give at least a week's notice before we start enforcing the updated rules.",
      'Adding on irrelevant banter not related to the purpose of a yell. Example: “WTS pebbles also Godmode sux” is not allowed.',
    ],
    discord: [
      'Do not post any personal information (email, phone number, address etc). It will be deleted from the chat. If you need to pass on something personal send it via a PM.',
      'Do not discuss anything sexual, racist, defaming. Anything considered spamming or trolling will be deleted and a warning will be issued. Any future spamming or trolling will result in a ban.',
    ],
  },
  links: [
    {
      url: 'https://discord.gg/MWtDws8',
      image:
        'https://vignette.wikia.nocookie.net/ffxi/images/0/08/Flag.jpg/revision/latest?cb=20060211183144',
      header: 'Eden Discord',
      description:
        'Join us on Discord for technical support, up-to-date annoucements, community events, memes, live chat with staff, and more.',
    },
    {
      url: 'http://classicffxi.wikia.com/wiki/Classic_FFXI_community',
      image: 'https://avatars2.githubusercontent.com/u/1171011?s=200&v=4',
      header: 'Eden Wiki',
      description:
        'This is a player led wiki open for everyone to edit. Although it is specific to Eden, it may have incorrect information due to the fact that it is not an official source of information.',
    },
    {
      url: 'https://github.com/EdenServer/community/issues',
      image: 'https://static.ffxiah.com/images/icon/17001.png',
      header: 'Bug Reports',
      description:
        'Eden has bugs too. :( See what issues we have and chime in if you found a bug!',
    },
    {
      url: 'https://ffxiclopedia.wikia.com/wiki/Main_Page',
      image:
        'https://vignette.wikia.nocookie.net/ffxi/images/b/b7/Favicon_Poroggo.png/revision/latest/scale-to-width-down/60?cb=20170308121952',
      header: 'FFXIclopedia',
      description:
        'The defacto go-to resource of this era. Keep in mind that this site has been updated post-era and you may need to browse history of the page to get more accurate data.',
    },
    {
      url: 'https://www.bg-wiki.com/',
      image: 'https://static.ffxiah.com/images/icon/15076.png',
      header: 'BG Wikipedia',
      description:
        "Another resource, however more updated that the era wiki. Can be a good place to get information that isn't provided by other sources.",
    },
    {
      url: 'http://campsitarus.blogspot.com/',
      image: 'https://www.bg-wiki.com/images/c/c3/Artemis%27s_Medal_icon.png',
      header: 'Campsitarus',
      description:
        'A great resource on era retail camps. Some camps will not apply as they are WoTG area camps.',
    },
    {
      url: 'http://ffxi-atlas.mageringnetwork.com/',
      image: 'https://static.ffxiah.com/images/icon/191.png',
      header: 'FFXI Atlas (Mirror)',
      description:
        'All the maps without the cost of buying your own maps in game. However, good luck finding where you are in relation to the map!',
    },
    {
      url: 'http://www.pyogenes.com/ffxi/timer/v2.html',
      image: 'https://static.ffxiah.com/images/icon/3706.png',
      header: 'Pyogenes Timer',
      description:
        "Pyogenes developed a Vana'Diel clock for retail. Eden runs on the same timer.",
    },
    {
      url: 'http://www.ffxidb.com/',
      image: 'http://www.ffxidb.com/public/img/xidb-logo-2.png',
      header: 'FFXIDB',
      description:
        'Common site to track drop rates of items. Keep in mind that drop rates stay updated when people use their plugin. With things like TH10 on current retail this data may be inaccurate.',
    },
    {
      url: 'http://ashita.atom0s.com/',
      image: 'https://www.ashitaxi.com/assets/img/ashita.ico',
      header: 'Ashita',
      description:
        'Eden officially supports Ashita v3 to enhance gameplay. Ashita v3 comes bundled with the Eden installer. You can find support for Ashita v3-specific things here.',
    },
    {
      url: 'http://windower.net/',
      image: 'http://windower.net/img/icon.png',
      header: 'Windower',
      description:
        'Windower 4 and 5 are not officially supported on Eden to enhance gameplay. While we do not offer setup or troubleshooting assistance, it does work on Eden.',
    },
  ],

  install: {
    source1: '',
    source2: '',
    bootloader: '',
    discord: 'https://discord.gg/MWtDws8',
  },
};
