# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        node-version: [16.x, 17.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Reconfigure git to use HTTP authentication
      # Workaround for npm bug:
      # https://github.com/actions/setup-node/issues/214#issuecomment-810829250
      # https://github.com/npm/cli/issues/2610
      run: >
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run ci:client
    - run: npm run check
    # Setting CI=false here, because when true, create-react-app treats warnings as errors, and we have a few warnings at the moment
    - env:
        CI: false
      run: npm run build
    - run: npm test
